//
// Created by Carlo Verdi on 24/10/23.
//

#ifndef PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_OBSERVER_H
#define PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_OBSERVER_H


class Observer {

};


#endif //PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_OBSERVER_H
