//
// Created by Carlo Verdi on 24/10/23.
//

#ifndef PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_SUBJECT_H
#define PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_SUBJECT_H


class Subject {

};


#endif //PROVA_ELABORATO_PROGRAMAZIONE_LISTA_SPESA_SUBJECT_H
